
- name: Add gpg repo keys
  apt_key:
    url: "{{ item }}"
  with_items:
    - "https://dl.yarnpkg.com/debian/pubkey.gpg"
    - "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

- name: Add repos
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "ppa:brightbox/ruby-ng"
    - "deb https://dl.yarnpkg.com/debian/ stable main"
    - "ppa:gophers/archive"
    - "deb https://deb.nodesource.com/node_8.x artful main"

- name: Remove ruby1.8
  apt:
    name: ruby1.8
    state: absent

- name: Update apt repositories cache
  apt:
    update_cache: yes
  changed_when: false

- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - sudo
    - build-essential
    - fakeroot
    - dpkg-dev
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libre2-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev
    - curl
    - openssh-server
    - checkinstall
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev
    - libicu-dev
    - logrotate
    - python-docutils
    - pkg-config
    - cmake
    - software-properties-common
    - ruby2.4
    - ruby2.4-dev
    - nodejs
    - golang-go
    - yarn
    - python-psycopg2
    - git
    - libpq-dev
    - libpq5
