---
- name: "Set owner of gitlab directory {{ gitlab_install_path }}"
  file:
    path: "{{ gitlab_install_path | mandatory }}"
    owner: git
    recurse: yes

- name: Place gitlab config
  template: 
    src: templates/gitlab.yml.j2
    dest: "{{ gitlab_install_path | mandatory }}/config/gitlab.yml"

- name: Copy secrets file
  template:
    src: templates/secrets.yml.j2
    dest: "{{ gitlab_install_path | mandatory }}/config/secrets.yml"
    mode: 0600
    owner: git

- name: Set owner of log directory
  file:
    path: "{{ gitlab_install_path | mandatory }}/log"
    owner: git
    mode: 0751

- name: Set owner of tmp directory
  file:
    path: "{{ gitlab_install_path | mandatory }}/tmp"
    owner: git
    mode: 0751

- name: Set permission on tmp/pids
  file:
    path: "{{ gitlab_install_path | mandatory }}/tmp/pids"
    mode: 0751

- name: Set permission on tmp/sockets
  file:
    path: "{{ gitlab_install_path | mandatory }}/tmp/sockets"
    mode: 0751

- name: Create public/uploads/ directory
  file:
    path: "{{ gitlab_install_path | mandatory }}/public/uploads"
    state: directory
    owner: git
    mode: 0700

- name: Change the permissions of the directory where CI job traces are stored
  file:
    path: "{{ gitlab_install_path | mandatory }}/builds"
    mode: 0751

- name: Change the permissions of the directory where CI artifacts are stored
  file:
    path: "{{ gitlab_install_path | mandatory }}/shared/artifacts/"
    mode: 0751

- name: Change the permissions of the directory where GitLab Pages are stored
  file:
    path: "{{ gitlab_install_path | mandatory }}/shared/pages/"
    mode: 0771
