---
- name: Place unicorn config 
  template:
    src: templates/unicorn.rb.j2
    dest: "{{ gitlab_install_path | mandatory }}/config/unicorn.rb"
  when: gitlab_unicorn_config_path is not defined

- name: Copy unicorn config
  copy: 
    src: "{{ gitlab_unicorn_config_path }}"
    dest: "{{ gitlab_install_path | mandatory }}/config/unicorn.rb"
  when: gitlab_unicorn_config_path is defined

- name: Copy the rack attack config
  copy:
    src: "{{ gitlab_rack_attack_config_path | default('files/rack_attack.rb')}}"
    dest: "{{ gitlab_install_path | mandatory }}/config/rack_attack.rb"

- name: Place resque config 
  template:
    src: templates/resque.yml.j2
    dest: "{{ gitlab_install_path | mandatory }}/config/resque.yml"

- name: Copy database config
  template:
    src: templates/database.yml.j2
    dest: "{{ gitlab_install_path | mandatory }}/config/database.yml"
    owner: git
    mode: 0640
