---
- name: "Set owner of gitlab directory {{ gitlab_install_path }}"
  file:
    path: "{{ gitlab_install_path | mandatory }}"
    owner: git
    recurse: yes

- name: Read default config
  include_vars:
    file: "gitlab.yml.defaults"
    name: gitlab_config_default

- name: Place GitLab config
  copy: 
    content: "{{ gitlab_config_default | combine(gitlab_config, recursive=True) | to_nice_yaml }}"
    dest: "{{ gitlab_install_path | mandatory }}/config/gitlab.yml"

- name: Write secrets file
  copy:
    content: "{{ gitlab_secret_config | to_nice_yaml }}"
    dest: "{{ gitlab_install_path | mandatory }}/config/secrets.yml"
    mode: 0600
    owner: git

- name: Create log directory
  file:
    path: "/var/log/gitlab"
    owner: git
    mode: 0750
    state: directory

- name: Delete old log directory
  file:
    path: "{{ gitlab_install_path | mandatory }}/log"
    state: absent

- name: Link log directory
  file:
    src: /var/log/gitlab/
    dest: "{{ gitlab_install_path | mandatory }}/log"
    state: link
    owner: git

- name: Set permission on tmp/pids
  file:
    path: "{{ gitlab_install_path | mandatory }}/tmp/pids"
    mode: 0750

- name: Set permission on tmp/sockets
  file:
    path: "{{ gitlab_install_path | mandatory }}/tmp/sockets"
    mode: 0750

- name: Create public/uploads/ directory
  file:
    path: "{{ gitlab_install_path | mandatory }}/public/uploads"
    state: directory
    owner: git
    mode: 0700

- name: Change the permissions of the directory where CI job traces are stored
  file:
    path: "{{ gitlab_install_path | mandatory }}/builds"
    mode: 0750

- name: Change the permissions of the directory where CI artifacts are stored
  file:
    path: "{{ gitlab_install_path | mandatory }}/shared/artifacts/"
    mode: 0750

- name: Change the permissions of the directory where GitLab Pages are stored
  file:
    path: "{{ gitlab_install_path | mandatory }}/shared/pages/"
    mode: 0770
