---
- name: Place unicorn config 
  template:
    src: unicorn.rb.j2
    dest: "{{ gitlab_install_path | mandatory }}/config/unicorn.rb"
  when: gitlab_unicorn_config_path is not defined

- name: Copy unicorn config
  copy: 
    src: "{{ gitlab_unicorn_config_path }}"
    dest: "{{ gitlab_install_path | mandatory }}/config/unicorn.rb"
  when: gitlab_unicorn_config_path is defined

- name: Copy the rack attack config
  copy:
    src: "{{ gitlab_rack_attack_config_path }}"
    dest: "{{ gitlab_install_path | mandatory }}/config/rack_attack.rb"

- name: Write resque config 
  copy:
    content: "{{ gitlab_resque_config | to_nice_yaml }}"
    dest: "{{ gitlab_install_path | mandatory }}/config/resque.yml"

- name: Write database config
  copy:
    content: "{{ gitlab_database_config | to_nice_yaml }}"
    dest: "{{ gitlab_install_path | mandatory }}/config/database.yml"
    owner: git
    mode: 0640
