---
- import_tasks: apt_install.yml
  when: ansible_pkg_mgr == "apt"

- name: Add gitlab user
  user:
      name: git
      shell: /bin/nologin
      comment: 'GitLab'
      state: present
      groups: redis

- name: Install bundler gem
  gem:
    name: bundler
  become: yes
  become_user: git

- import_tasks: postgres_install.yml

- name: Creates redis socket directory
  file:
    path: "{{redis_unixsocket | dirname }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Clone gitlab to {{gitlab_install_path | mandatory}}
  git:
    depth: 1
    repo: https://gitlab.com/gitlab-org/gitlab-ee.git
    dest: "{{ gitlab_install_path | mandatory }}"
    version: "{{ gitlab_version_number | mandatory }}"
    force: yes
  when: gitlab_version == "ee"

- name: Clone gitlab to {{gitlab_install_path}}
  git:
    depth: 1
    repo: https://gitlab.com/gitlab-org/gitlab-ce.git
    dest: "{{ gitlab_install_path | mandatory}}"
    version: "{{ gitlab_version_number }}"
    force: yes
  when: gitlab_version == "ce"

- name: "Set owner of gitlab directory {{gitlab_install_path}}"
  file:
    path: "{{ gitlab_install_path | mandatory}}"
    owner: git
    recurse: yes

- name: Place gitlab config
  template: 
    src: templates/gitlab.yml.j2
    dest: "{{ gitlab_install_path | mandatory}}/config/gitlab.yml"

- name: Copy secrets file
  template:
    src: templates/secrets.yml.j2
    dest: "{{ gitlab_install_path | mandatory}}/config/secrets.yml"
    mode: 0600
    owner: git

- name: Set owner of log directory
  file:
    path: "{{ gitlab_install_path | mandatory}}/log"
    owner: git
    mode: 0751

- name: Set owner of tmp directory
  file:
    path: "{{ gitlab_install_path | mandatory}}/tmp"
    owner: git
    mode: 0751

- name: Set permission on tmp/pids
  file:
    path: "{{ gitlab_install_path | mandatory}}/tmp/pids"
    mode: 0751

- name: Set permission on tmp/sockets
  file:
    path: "{{ gitlab_install_path | mandatory}}/tmp/sockets"
    mode: 0751

- name: Create public/uploads/ directory
  file:
    path: "{{ gitlab_install_path | mandatory}}/public/uploads"
    state: directory
    owner: git
    mode: 0700

- name: Change the permissions of the directory where CI job traces are stored
  file:
    path: "{{ gitlab_install_path | mandatory}}/builds"
    mode: 0751

- name: Change the permissions of the directory where CI artifacts are stored
  file:
    path: "{{ gitlab_install_path | mandatory}}/shared/artifacts/"
    mode: 0751

- name: Change the permissions of the directory where GitLab Pages are stored
  file:
    path: "{{ gitlab_install_path | mandatory}}/shared/pages/"
    mode: 0771

- name: Place unicorn config 
  template:
    src: templates/unicorn.rb.j2
    dest: "{{ gitlab_install_path | mandatory}}/config/unicorn.rb"
  when: gitlab_unicorn_config_path is not defined

- name: Copy unicorn config owner
  copy: 
    src: "{{gitlab_unicorn_config_path}}"
    dest: "{{ gitlab_install_path | mandatory}}/config/unicorn.rb"
  when: gitlab_unicorn_config_path is defined

- name: Copy the rack attack config
  copy:
    src: "{{gitlab_rack_attack_config_path}}"
    dest: "{{ gitlab_install_path | mandatory}}/config/rack_attack.rb"
  when: gitlab_rack_attack_config_path is defined

- name: Copy the rack attack config
  copy:
    src: "files/rack_attack.rb"
    dest: "{{ gitlab_install_path | mandatory}}/config/rack_attack.rb"
  when: gitlab_rack_attack_config_path is not defined

- name: Configure Git global settings for git user
  git_config:
    name: core.autocrlfs
    scope: global
    value: input

- name: Disable 'git gc --auto' because GitLab already runs 'git gc' when needed
  git_config:
    name: gc.auto
    scope: global
    value: 0

- name: Enable packfile bitmaps
  git_config:
    name: repack.writeBitmaps
    scope: global
    value: true

- name: Place resque config 
  template:
    src: templates/resque.yml.j2
    dest: "{{ gitlab_install_path | mandatory}}/config/resque.yml"

- name: Copy database config
  template:
    src: templates/database.yml.j2
    dest: "{{ gitlab_install_path | mandatory}}/config/database.yml"
    owner: git
    mode: 0640

- name: Create Bundler directories
  file:
    path: "{{ gitlab_install_path | mandatory}}/{{item}}"
    state: directory
    owner: git
  with_items:
    - ".bundle"
    - "vernder/"

- name: Install gems with bundler
  bundler:
    state: present
    deployment_mode: yes
    gemfile: "{{ gitlab_install_path | mandatory}}/Gemfile"
    exclude_groups: 
      - development
      - test
      - aws
      - mysql
      - kerberos
  become: yes
  become_user: git

- name: Install gitlab shell
  command: "sudo -u git -H bundle exec rake gitlab:shell:install REDIS_URL=unix:{{redis_unixsocket}} RAILS_ENV=production SKIP_STORAGE_VALIDATION=true"
  args:
    chdir: "{{ gitlab_install_path | mandatory}}"

- name: Install gitlab-workhorse
  command: 'sudo -u git -H bundle exec rake "gitlab:workhorse:install[/home/git/gitlab-workhorse]" RAILS_ENV=production'
  args:
    chdir: "{{ gitlab_install_path | mandatory}}"

- name: Initialize database and activate advanced features
  shell:
    cmd: 'yes "yes" | sudo -u git -H bundle exec rake gitlab:setup RAILS_ENV=production GITLAB_ROOT_PASSWORD={{gitlab_root_password|mandatory}} GITLAB_ROOT_EMAIL={{gitlab_root_mail|mandatory}}'  
    chdir: "{{ gitlab_install_path | mandatory}}"
  async: 31557600 # Wait up to one year for completion
  poll: 30

- name: Set privileges on database
  postgresql_privs:
    db: "{{gitlab_db_name}}"
    privs: ALL
    type: database
    role: "{{gitlab_db_user}}"
    unix_socket: "{{postgres_run_directory}}"

- name: Set priviliges on tables
  postgresql_privs:
    db: "{{gitlab_db_name}}"
    privs: ALL
    type: table
    objs: ALL_IN_SCHEMA
    role: "{{gitlab_db_user}}"
    unix_socket: "{{postgres_run_directory}}"

- name: Set priviliges on sequences
  postgresql_privs:
    db: "{{gitlab_db_name}}"
    privs: ALL
    type: sequence
    objs: ALL_IN_SCHEMA
    role: "{{gitlab_db_user}}"
    unix_socket: "{{postgres_run_directory}}"

- name: Download systemd service files from gitlab
  get_url:
    url:  "https://gitlab.com/gitlab-org/gitlab-recipes/raw/master/init/systemd/{{item}}"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - gitlab-sidekiq.service
    - gitlab-unicorn.service
    - gitlab-workhorse.service
    - gitlab-mailroom.service
    - gitlab-gitaly.service

- name: Fetch Gitaly source with git and compile with go
  command: 'sudo -u git -H bundle exec rake "gitlab:gitaly:install[/home/git/gitaly]" RAILS_ENV=production'
  args:
    chdir: "{{ gitlab_install_path | mandatory}}"

- name: Restrict Gitaly socket access
  file:
    path: "{{ gitlab_install_path | mandatory}}/tmp/sockets/private"
    owner: git
    mode: 0700

- name: Setup Logrotate
  copy:
    src: "{{ gitlab_install_path | mandatory}}/lib/support/logrotate/gitlab"
    dest: /etc/logrotate.d/gitlab
    remote_src: yes

- name: Compile GetText PO files
  command: 'sudo -u git -H bundle exec rake gettext:pack RAILS_ENV=production'
  args:
    chdir: "{{ gitlab_install_path | mandatory}}"

- name: Compile GetText PO files
  command: 'sudo -u git -H bundle exec rake gettext:po_to_json RAILS_ENV=production'
  args:
    chdir: "{{ gitlab_install_path | mandatory}}"

- name: Compile Assets
  command: 'sudo -u git -H yarn install --production --pure-lockfile'
  args:
    chdir: "{{ gitlab_install_path | mandatory}}"

- name: Compile Assets
  command: 'sudo -u git -H bundle exec rake gitlab:assets:compile RAILS_ENV=production NODE_ENV=production'
  args:
    chdir: "{{ gitlab_install_path | mandatory}}"

- name: Enable and start GitLab services
  systemd: 
    state: started
    enabled: yes
    daemon_reload: yes
    name: "{{item}}"
  with_items:
    - gitlab-sidekiq.service
    - gitlab-unicorn.service
    - gitlab-workhorse.service
    - gitlab-mailroom.service
    - gitlab-gitaly.service

