---
- name: Reload and restart systemd daemon
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{ item }}"
  with_items:
    - gitlab-sidekiq.service
    - gitlab-unicorn.service
    - gitlab-workhorse.service
    - gitlab-mailroom.service
    - gitlab-gitaly.service
